apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubelet-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: kubelet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubelet
  template:
    metadata:
      labels:
        app: kubelet
    spec:
      containers:
      - name: kubelet
        image: {{ .Values.kubelet.image.repository }}:{{ .Values.kubelet.image.tag }}